# Generated by Django 2.2.13 on 2020-08-14 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200808_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='song.Language'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='song.Song'),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lyricrequest',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_requests', to='song.Language'),
        ),
        migrations.AlterField(
            model_name='lyricrequest',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_requests', to='song.Song'),
        ),
        migrations.AlterField(
            model_name='lyricrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Category'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='song.Language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='lyric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='song.Lyric'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
