# Generated by Django 2.2.13 on 2020-06-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_lyric_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
