# Generated by Django 2.2.13 on 2020-08-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200814_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
