# Generated by Django 2.2.13 on 2020-06-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20200620_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='category',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='language',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='lyricrequest',
            name='date_requested',
        ),
        migrations.RemoveField(
            model_name='song',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='songlink',
            name='dete_added',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='date_added',
        ),
    ]
