# Generated by Django 2.2.13 on 2020-06-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_auto_20200622_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
